/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ARCH_X86 1

#define ARCH_X86_64 1

#define GEGL_LIBRARY "gegl-0.4"

#define GEGL_MAJOR_VERSION 0

#define GEGL_MICRO_VERSION 39

#define GEGL_MINOR_VERSION 4

#define GEGL_UNSTABLE

#define GETTEXT_PACKAGE "gegl-0.4"

#define HAVE_EXECINFO_H

#define HAVE_FSYNC

#define HAVE_GEXIV2

#define HAVE_LUA

#define HAVE_MALLOC_TRIM

#undef HAVE_MRG

#define HAVE_OPENMP

#define HAVE_STRPTIME

#define HAVE_SUITESPARSE_UMFPACK_H

#undef HAVE_UMFPACK_H

#define HAVE_UNISTD_H

